//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMain.DBLSoftTechServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="DBLSoftTechServiceReference.ClientOpeningWS")]
    public interface ClientOpeningWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/ClientOpeningWS/openClientRequest", ReplyAction="http://ws/ClientOpeningWS/openClientResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AppMain.DBLSoftTechServiceReference.openClientResponse openClient(AppMain.DBLSoftTechServiceReference.openClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/ClientOpeningWS/openClientRequest", ReplyAction="http://ws/ClientOpeningWS/openClientResponse")]
        System.Threading.Tasks.Task<AppMain.DBLSoftTechServiceReference.openClientResponse> openClientAsync(AppMain.DBLSoftTechServiceReference.openClientRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class clientAofApiBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accStatmentFreqField;
        
        private string accountTypeField;
        
        private string appIdField;
        
        private string applicantObjField;
        
        private string approximateAnnualIncomeField;
        
        private string authPersonCityField;
        
        private string authPersonCountryField;
        
        private string authPersonEmailField;
        
        private string authPersonFaxField;
        
        private string authPersonFullNameField;
        
        private string authPersonMailingAddField;
        
        private string authPersonMobField;
        
        private string authPersonNicExpDateField;
        
        private string authPersonNicIssueAuthorityField;
        
        private string authPersonNicIssueDateField;
        
        private string authPersonNicPhotoIdField;
        
        private string authPersonRelationField;
        
        private string authPersonTelField;
        
        private string authPersonUploadNicImgIDField;
        
        private string authPersonZipCodeField;
        
        private string branchField;
        
        private string cityAddField;
        
        private string commBankAccNameField;
        
        private string commBankAccNoField;
        
        private string commBankBranchField;
        
        private string commBankSelectionField;
        
        private string countryAddField;
        
        private string courtConvictionField;
        
        private string courtConvictionDetailField;
        
        private string currentEmployerField;
        
        private string currentEmployerAddField;
        
        private string currentOccupationField;
        
        private string declarationField;
        
        private string dobField;
        
        private string emailField;
        
        private string employmentFromDateField;
        
        private string employmentStatusField;
        
        private string employmentToDateField;
        
        private string expDateField;
        
        private string expectedAccActivityField;
        
        private string faxField;
        
        private string firstKinEmailField;
        
        private string firstKinFaxNumField;
        
        private string firstKinMailingAddField;
        
        private string firstKinMobNumField;
        
        private string firstKinNameField;
        
        private string firstKinRelationField;
        
        private string firstKinTelNumField;
        
        private string firstNameField;
        
        private string genderField;
        
        private string incomeFundSourceField;
        
        private string investmentHorizonField;
        
        private string investmentKnowledgeField;
        
        private string investmentTypeField;
        
        private string issueDateField;
        
        private string madenNameField;
        
        private string mailingAddField;
        
        private string mailingAddCityField;
        
        private string mailingAddCountryField;
        
        private string mailingAddZipCodeField;
        
        private string maritialStatusField;
        
        private string mobileNumField;
        
        private string modeOfInstructionField;
        
        private string modeOfNotificationField;
        
        private string motherMadenNameField;
        
        private string nationalityField;
        
        private string netWorthField;
        
        private string nicIssueAuthField;
        
        private string nicNumField;
        
        private string nicPhotoIdTypeField;
        
        private string nomineeTrustField;
        
        private string nomineeTrustNameField;
        
        private string occupationField;
        
        private string onlineTradingFacField;
        
        private string otherNameField;
        
        private string previousEmployerField;
        
        private string previousOccupationField;
        
        private string residentialAddField;
        
        private string riskTolerenceField;
        
        private string secKinEmailField;
        
        private string secKinFaxField;
        
        private string secKinFullNameField;
        
        private string secKinMailingAddField;
        
        private string secKinMobNumField;
        
        private string secKinRelationField;
        
        private string secKinTelNumField;
        
        private string signImgIdField;
        
        private string signNumField;
        
        private string srNameField;
        
        private string suffixField;
        
        private string swiftSortCodeField;
        
        private string taxIdNoField;
        
        private string tellephoneNumField;
        
        private string titleField;
        
        private string totEmploymentYearField;
        
        private string uploadImgIdField;
        
        private string zipCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string accStatmentFreq {
            get {
                return this.accStatmentFreqField;
            }
            set {
                this.accStatmentFreqField = value;
                this.RaisePropertyChanged("accStatmentFreq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string accountType {
            get {
                return this.accountTypeField;
            }
            set {
                this.accountTypeField = value;
                this.RaisePropertyChanged("accountType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string appId {
            get {
                return this.appIdField;
            }
            set {
                this.appIdField = value;
                this.RaisePropertyChanged("appId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string applicantObj {
            get {
                return this.applicantObjField;
            }
            set {
                this.applicantObjField = value;
                this.RaisePropertyChanged("applicantObj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string approximateAnnualIncome {
            get {
                return this.approximateAnnualIncomeField;
            }
            set {
                this.approximateAnnualIncomeField = value;
                this.RaisePropertyChanged("approximateAnnualIncome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string authPersonCity {
            get {
                return this.authPersonCityField;
            }
            set {
                this.authPersonCityField = value;
                this.RaisePropertyChanged("authPersonCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string authPersonCountry {
            get {
                return this.authPersonCountryField;
            }
            set {
                this.authPersonCountryField = value;
                this.RaisePropertyChanged("authPersonCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string authPersonEmail {
            get {
                return this.authPersonEmailField;
            }
            set {
                this.authPersonEmailField = value;
                this.RaisePropertyChanged("authPersonEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string authPersonFax {
            get {
                return this.authPersonFaxField;
            }
            set {
                this.authPersonFaxField = value;
                this.RaisePropertyChanged("authPersonFax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string authPersonFullName {
            get {
                return this.authPersonFullNameField;
            }
            set {
                this.authPersonFullNameField = value;
                this.RaisePropertyChanged("authPersonFullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string authPersonMailingAdd {
            get {
                return this.authPersonMailingAddField;
            }
            set {
                this.authPersonMailingAddField = value;
                this.RaisePropertyChanged("authPersonMailingAdd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string authPersonMob {
            get {
                return this.authPersonMobField;
            }
            set {
                this.authPersonMobField = value;
                this.RaisePropertyChanged("authPersonMob");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string authPersonNicExpDate {
            get {
                return this.authPersonNicExpDateField;
            }
            set {
                this.authPersonNicExpDateField = value;
                this.RaisePropertyChanged("authPersonNicExpDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string authPersonNicIssueAuthority {
            get {
                return this.authPersonNicIssueAuthorityField;
            }
            set {
                this.authPersonNicIssueAuthorityField = value;
                this.RaisePropertyChanged("authPersonNicIssueAuthority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string authPersonNicIssueDate {
            get {
                return this.authPersonNicIssueDateField;
            }
            set {
                this.authPersonNicIssueDateField = value;
                this.RaisePropertyChanged("authPersonNicIssueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string authPersonNicPhotoId {
            get {
                return this.authPersonNicPhotoIdField;
            }
            set {
                this.authPersonNicPhotoIdField = value;
                this.RaisePropertyChanged("authPersonNicPhotoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string authPersonRelation {
            get {
                return this.authPersonRelationField;
            }
            set {
                this.authPersonRelationField = value;
                this.RaisePropertyChanged("authPersonRelation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string authPersonTel {
            get {
                return this.authPersonTelField;
            }
            set {
                this.authPersonTelField = value;
                this.RaisePropertyChanged("authPersonTel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string authPersonUploadNicImgID {
            get {
                return this.authPersonUploadNicImgIDField;
            }
            set {
                this.authPersonUploadNicImgIDField = value;
                this.RaisePropertyChanged("authPersonUploadNicImgID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string authPersonZipCode {
            get {
                return this.authPersonZipCodeField;
            }
            set {
                this.authPersonZipCodeField = value;
                this.RaisePropertyChanged("authPersonZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string branch {
            get {
                return this.branchField;
            }
            set {
                this.branchField = value;
                this.RaisePropertyChanged("branch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string cityAdd {
            get {
                return this.cityAddField;
            }
            set {
                this.cityAddField = value;
                this.RaisePropertyChanged("cityAdd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string commBankAccName {
            get {
                return this.commBankAccNameField;
            }
            set {
                this.commBankAccNameField = value;
                this.RaisePropertyChanged("commBankAccName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string commBankAccNo {
            get {
                return this.commBankAccNoField;
            }
            set {
                this.commBankAccNoField = value;
                this.RaisePropertyChanged("commBankAccNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string commBankBranch {
            get {
                return this.commBankBranchField;
            }
            set {
                this.commBankBranchField = value;
                this.RaisePropertyChanged("commBankBranch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string commBankSelection {
            get {
                return this.commBankSelectionField;
            }
            set {
                this.commBankSelectionField = value;
                this.RaisePropertyChanged("commBankSelection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string countryAdd {
            get {
                return this.countryAddField;
            }
            set {
                this.countryAddField = value;
                this.RaisePropertyChanged("countryAdd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string courtConviction {
            get {
                return this.courtConvictionField;
            }
            set {
                this.courtConvictionField = value;
                this.RaisePropertyChanged("courtConviction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string courtConvictionDetail {
            get {
                return this.courtConvictionDetailField;
            }
            set {
                this.courtConvictionDetailField = value;
                this.RaisePropertyChanged("courtConvictionDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string currentEmployer {
            get {
                return this.currentEmployerField;
            }
            set {
                this.currentEmployerField = value;
                this.RaisePropertyChanged("currentEmployer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string currentEmployerAdd {
            get {
                return this.currentEmployerAddField;
            }
            set {
                this.currentEmployerAddField = value;
                this.RaisePropertyChanged("currentEmployerAdd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string currentOccupation {
            get {
                return this.currentOccupationField;
            }
            set {
                this.currentOccupationField = value;
                this.RaisePropertyChanged("currentOccupation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string declaration {
            get {
                return this.declarationField;
            }
            set {
                this.declarationField = value;
                this.RaisePropertyChanged("declaration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string dob {
            get {
                return this.dobField;
            }
            set {
                this.dobField = value;
                this.RaisePropertyChanged("dob");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string employmentFromDate {
            get {
                return this.employmentFromDateField;
            }
            set {
                this.employmentFromDateField = value;
                this.RaisePropertyChanged("employmentFromDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string employmentStatus {
            get {
                return this.employmentStatusField;
            }
            set {
                this.employmentStatusField = value;
                this.RaisePropertyChanged("employmentStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string employmentToDate {
            get {
                return this.employmentToDateField;
            }
            set {
                this.employmentToDateField = value;
                this.RaisePropertyChanged("employmentToDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string expDate {
            get {
                return this.expDateField;
            }
            set {
                this.expDateField = value;
                this.RaisePropertyChanged("expDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string expectedAccActivity {
            get {
                return this.expectedAccActivityField;
            }
            set {
                this.expectedAccActivityField = value;
                this.RaisePropertyChanged("expectedAccActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
                this.RaisePropertyChanged("fax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string firstKinEmail {
            get {
                return this.firstKinEmailField;
            }
            set {
                this.firstKinEmailField = value;
                this.RaisePropertyChanged("firstKinEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string firstKinFaxNum {
            get {
                return this.firstKinFaxNumField;
            }
            set {
                this.firstKinFaxNumField = value;
                this.RaisePropertyChanged("firstKinFaxNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string firstKinMailingAdd {
            get {
                return this.firstKinMailingAddField;
            }
            set {
                this.firstKinMailingAddField = value;
                this.RaisePropertyChanged("firstKinMailingAdd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string firstKinMobNum {
            get {
                return this.firstKinMobNumField;
            }
            set {
                this.firstKinMobNumField = value;
                this.RaisePropertyChanged("firstKinMobNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string firstKinName {
            get {
                return this.firstKinNameField;
            }
            set {
                this.firstKinNameField = value;
                this.RaisePropertyChanged("firstKinName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string firstKinRelation {
            get {
                return this.firstKinRelationField;
            }
            set {
                this.firstKinRelationField = value;
                this.RaisePropertyChanged("firstKinRelation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public string firstKinTelNum {
            get {
                return this.firstKinTelNumField;
            }
            set {
                this.firstKinTelNumField = value;
                this.RaisePropertyChanged("firstKinTelNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=48)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=49)]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=50)]
        public string incomeFundSource {
            get {
                return this.incomeFundSourceField;
            }
            set {
                this.incomeFundSourceField = value;
                this.RaisePropertyChanged("incomeFundSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=51)]
        public string investmentHorizon {
            get {
                return this.investmentHorizonField;
            }
            set {
                this.investmentHorizonField = value;
                this.RaisePropertyChanged("investmentHorizon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=52)]
        public string investmentKnowledge {
            get {
                return this.investmentKnowledgeField;
            }
            set {
                this.investmentKnowledgeField = value;
                this.RaisePropertyChanged("investmentKnowledge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=53)]
        public string investmentType {
            get {
                return this.investmentTypeField;
            }
            set {
                this.investmentTypeField = value;
                this.RaisePropertyChanged("investmentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=54)]
        public string issueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
                this.RaisePropertyChanged("issueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=55)]
        public string madenName {
            get {
                return this.madenNameField;
            }
            set {
                this.madenNameField = value;
                this.RaisePropertyChanged("madenName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=56)]
        public string mailingAdd {
            get {
                return this.mailingAddField;
            }
            set {
                this.mailingAddField = value;
                this.RaisePropertyChanged("mailingAdd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=57)]
        public string mailingAddCity {
            get {
                return this.mailingAddCityField;
            }
            set {
                this.mailingAddCityField = value;
                this.RaisePropertyChanged("mailingAddCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=58)]
        public string mailingAddCountry {
            get {
                return this.mailingAddCountryField;
            }
            set {
                this.mailingAddCountryField = value;
                this.RaisePropertyChanged("mailingAddCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=59)]
        public string mailingAddZipCode {
            get {
                return this.mailingAddZipCodeField;
            }
            set {
                this.mailingAddZipCodeField = value;
                this.RaisePropertyChanged("mailingAddZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=60)]
        public string maritialStatus {
            get {
                return this.maritialStatusField;
            }
            set {
                this.maritialStatusField = value;
                this.RaisePropertyChanged("maritialStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=61)]
        public string mobileNum {
            get {
                return this.mobileNumField;
            }
            set {
                this.mobileNumField = value;
                this.RaisePropertyChanged("mobileNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=62)]
        public string modeOfInstruction {
            get {
                return this.modeOfInstructionField;
            }
            set {
                this.modeOfInstructionField = value;
                this.RaisePropertyChanged("modeOfInstruction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=63)]
        public string modeOfNotification {
            get {
                return this.modeOfNotificationField;
            }
            set {
                this.modeOfNotificationField = value;
                this.RaisePropertyChanged("modeOfNotification");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=64)]
        public string motherMadenName {
            get {
                return this.motherMadenNameField;
            }
            set {
                this.motherMadenNameField = value;
                this.RaisePropertyChanged("motherMadenName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=65)]
        public string nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
                this.RaisePropertyChanged("nationality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=66)]
        public string netWorth {
            get {
                return this.netWorthField;
            }
            set {
                this.netWorthField = value;
                this.RaisePropertyChanged("netWorth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=67)]
        public string nicIssueAuth {
            get {
                return this.nicIssueAuthField;
            }
            set {
                this.nicIssueAuthField = value;
                this.RaisePropertyChanged("nicIssueAuth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=68)]
        public string nicNum {
            get {
                return this.nicNumField;
            }
            set {
                this.nicNumField = value;
                this.RaisePropertyChanged("nicNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=69)]
        public string nicPhotoIdType {
            get {
                return this.nicPhotoIdTypeField;
            }
            set {
                this.nicPhotoIdTypeField = value;
                this.RaisePropertyChanged("nicPhotoIdType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=70)]
        public string nomineeTrust {
            get {
                return this.nomineeTrustField;
            }
            set {
                this.nomineeTrustField = value;
                this.RaisePropertyChanged("nomineeTrust");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=71)]
        public string nomineeTrustName {
            get {
                return this.nomineeTrustNameField;
            }
            set {
                this.nomineeTrustNameField = value;
                this.RaisePropertyChanged("nomineeTrustName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=72)]
        public string occupation {
            get {
                return this.occupationField;
            }
            set {
                this.occupationField = value;
                this.RaisePropertyChanged("occupation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=73)]
        public string onlineTradingFac {
            get {
                return this.onlineTradingFacField;
            }
            set {
                this.onlineTradingFacField = value;
                this.RaisePropertyChanged("onlineTradingFac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=74)]
        public string otherName {
            get {
                return this.otherNameField;
            }
            set {
                this.otherNameField = value;
                this.RaisePropertyChanged("otherName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=75)]
        public string previousEmployer {
            get {
                return this.previousEmployerField;
            }
            set {
                this.previousEmployerField = value;
                this.RaisePropertyChanged("previousEmployer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=76)]
        public string previousOccupation {
            get {
                return this.previousOccupationField;
            }
            set {
                this.previousOccupationField = value;
                this.RaisePropertyChanged("previousOccupation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=77)]
        public string residentialAdd {
            get {
                return this.residentialAddField;
            }
            set {
                this.residentialAddField = value;
                this.RaisePropertyChanged("residentialAdd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=78)]
        public string riskTolerence {
            get {
                return this.riskTolerenceField;
            }
            set {
                this.riskTolerenceField = value;
                this.RaisePropertyChanged("riskTolerence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=79)]
        public string secKinEmail {
            get {
                return this.secKinEmailField;
            }
            set {
                this.secKinEmailField = value;
                this.RaisePropertyChanged("secKinEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=80)]
        public string secKinFax {
            get {
                return this.secKinFaxField;
            }
            set {
                this.secKinFaxField = value;
                this.RaisePropertyChanged("secKinFax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=81)]
        public string secKinFullName {
            get {
                return this.secKinFullNameField;
            }
            set {
                this.secKinFullNameField = value;
                this.RaisePropertyChanged("secKinFullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=82)]
        public string secKinMailingAdd {
            get {
                return this.secKinMailingAddField;
            }
            set {
                this.secKinMailingAddField = value;
                this.RaisePropertyChanged("secKinMailingAdd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=83)]
        public string secKinMobNum {
            get {
                return this.secKinMobNumField;
            }
            set {
                this.secKinMobNumField = value;
                this.RaisePropertyChanged("secKinMobNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=84)]
        public string secKinRelation {
            get {
                return this.secKinRelationField;
            }
            set {
                this.secKinRelationField = value;
                this.RaisePropertyChanged("secKinRelation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=85)]
        public string secKinTelNum {
            get {
                return this.secKinTelNumField;
            }
            set {
                this.secKinTelNumField = value;
                this.RaisePropertyChanged("secKinTelNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=86)]
        public string signImgId {
            get {
                return this.signImgIdField;
            }
            set {
                this.signImgIdField = value;
                this.RaisePropertyChanged("signImgId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=87)]
        public string signNum {
            get {
                return this.signNumField;
            }
            set {
                this.signNumField = value;
                this.RaisePropertyChanged("signNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=88)]
        public string srName {
            get {
                return this.srNameField;
            }
            set {
                this.srNameField = value;
                this.RaisePropertyChanged("srName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=89)]
        public string suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
                this.RaisePropertyChanged("suffix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=90)]
        public string swiftSortCode {
            get {
                return this.swiftSortCodeField;
            }
            set {
                this.swiftSortCodeField = value;
                this.RaisePropertyChanged("swiftSortCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=91)]
        public string taxIdNo {
            get {
                return this.taxIdNoField;
            }
            set {
                this.taxIdNoField = value;
                this.RaisePropertyChanged("taxIdNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=92)]
        public string tellephoneNum {
            get {
                return this.tellephoneNumField;
            }
            set {
                this.tellephoneNumField = value;
                this.RaisePropertyChanged("tellephoneNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=93)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=94)]
        public string totEmploymentYear {
            get {
                return this.totEmploymentYearField;
            }
            set {
                this.totEmploymentYearField = value;
                this.RaisePropertyChanged("totEmploymentYear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=95)]
        public string uploadImgId {
            get {
                return this.uploadImgIdField;
            }
            set {
                this.uploadImgIdField = value;
                this.RaisePropertyChanged("uploadImgId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=96)]
        public string zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("zipCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class results : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="openClient", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class openClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AppMain.DBLSoftTechServiceReference.clientAofApiBean arg0;
        
        public openClientRequest() {
        }
        
        public openClientRequest(AppMain.DBLSoftTechServiceReference.clientAofApiBean arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="openClientResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class openClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AppMain.DBLSoftTechServiceReference.results @return;
        
        public openClientResponse() {
        }
        
        public openClientResponse(AppMain.DBLSoftTechServiceReference.results @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientOpeningWSChannel : AppMain.DBLSoftTechServiceReference.ClientOpeningWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientOpeningWSClient : System.ServiceModel.ClientBase<AppMain.DBLSoftTechServiceReference.ClientOpeningWS>, AppMain.DBLSoftTechServiceReference.ClientOpeningWS {
        
        public ClientOpeningWSClient() {
        }
        
        public ClientOpeningWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientOpeningWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientOpeningWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientOpeningWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppMain.DBLSoftTechServiceReference.openClientResponse AppMain.DBLSoftTechServiceReference.ClientOpeningWS.openClient(AppMain.DBLSoftTechServiceReference.openClientRequest request) {
            return base.Channel.openClient(request);
        }
        
        public AppMain.DBLSoftTechServiceReference.results openClient(AppMain.DBLSoftTechServiceReference.clientAofApiBean arg0) {
            AppMain.DBLSoftTechServiceReference.openClientRequest inValue = new AppMain.DBLSoftTechServiceReference.openClientRequest();
            inValue.arg0 = arg0;
            AppMain.DBLSoftTechServiceReference.openClientResponse retVal = ((AppMain.DBLSoftTechServiceReference.ClientOpeningWS)(this)).openClient(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppMain.DBLSoftTechServiceReference.openClientResponse> AppMain.DBLSoftTechServiceReference.ClientOpeningWS.openClientAsync(AppMain.DBLSoftTechServiceReference.openClientRequest request) {
            return base.Channel.openClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppMain.DBLSoftTechServiceReference.openClientResponse> openClientAsync(AppMain.DBLSoftTechServiceReference.clientAofApiBean arg0) {
            AppMain.DBLSoftTechServiceReference.openClientRequest inValue = new AppMain.DBLSoftTechServiceReference.openClientRequest();
            inValue.arg0 = arg0;
            return ((AppMain.DBLSoftTechServiceReference.ClientOpeningWS)(this)).openClientAsync(inValue);
        }
    }
}
