//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountEditRequest
    {
        public System.Guid Id { get; set; }
        public System.Guid AccountId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ErrorList { get; set; }
        public bool IsActive { get; set; }
        public bool DBLFormEnabled { get; set; }
        public bool FileUploadEnabled { get; set; }
        public bool AMLEnabled { get; set; }
        public bool ETIEnabled { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
