//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountSettlementDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid AccountId { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> CorrespondentBankId { get; set; }
        public Nullable<int> IntermediaryBankId { get; set; }
        public string Branch { get; set; }
        public string SwiftCode { get; set; }
        public string CorrespondentBankSwiftCode { get; set; }
        public string IntermediaryBankSwiftCode { get; set; }
        public string NameOfBeneficiary { get; set; }
        public string BIC { get; set; }
        public string MarginTradingOption { get; set; }
        public string OnlineTradingFacility { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
