//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountCheckList
    {
        public System.Guid Id { get; set; }
        public System.Guid AccountId { get; set; }
        public int CheckListItemId { get; set; }
        public bool IsChecked { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual CheckListItem CheckListItem { get; set; }
    }
}
