//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountMember
    {
        public System.Guid Id { get; set; }
        public System.Guid AccountId { get; set; }
        public Nullable<int> TitleId { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Othername { get; set; }
        public Nullable<int> NationalityId { get; set; }
        public string DOB { get; set; }
        public string PlaceOfBirth { get; set; }
        public Nullable<int> MaritalStatusId { get; set; }
        public string MothersMaidenName { get; set; }
        public string ResidentialAddressFull { get; set; }
        public string ResidentialCity { get; set; }
        public string ResidentialZipCode { get; set; }
        public Nullable<int> ResidentialCountryId { get; set; }
        public string MailingAddressFull { get; set; }
        public string MailingAddressCity { get; set; }
        public string MailingAddressZipCode { get; set; }
        public Nullable<int> MailingAddressCountryId { get; set; }
        public Nullable<int> SelectWhereApplicableId { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Occupation { get; set; }
        public Nullable<int> IdTypeId { get; set; }
        public string IdNumber { get; set; }
        public string IssuingAuthority { get; set; }
        public string IdCardIssueDate { get; set; }
        public string IdCardExpiryDate { get; set; }
        public string IdPath { get; set; }
        public string SignaturePath { get; set; }
        public string MaidenName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Gender { get; set; }
        public bool IdValidated { get; set; }
        public Nullable<System.DateTime> IdValidationDate { get; set; }
        public string IdValidationBy { get; set; }
        public string IdValidationMode { get; set; }
        public string ManualValidationComment { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual Country Country2 { get; set; }
        public virtual MaritalStatu MaritalStatu { get; set; }
        public virtual Title Title { get; set; }
    }
}
