//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountAuthorisedPerson
    {
        public System.Guid Id { get; set; }
        public System.Guid AccountId { get; set; }
        public string Name { get; set; }
        public Nullable<int> TitleId { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string RelationToAccountHolder { get; set; }
        public string MailingAddress { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> IdType { get; set; }
        public string IdNumber { get; set; }
        public string IssueDate { get; set; }
        public string IDExpiryDate { get; set; }
        public string IdIssueAuthority { get; set; }
        public string IdPath { get; set; }
        public string SignaturePath { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
