//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInstructionEmploymentDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid AccountId { get; set; }
        public Nullable<int> ModeOfInstructionId { get; set; }
        public Nullable<int> ModeOfNotificationId { get; set; }
        public Nullable<int> SourceOfFundId { get; set; }
        public Nullable<int> EmploymentStatusId { get; set; }
        public string PrevOccupation { get; set; }
        public string PrevEmployer { get; set; }
        public string CurrentOccupation { get; set; }
        public string CurrentEmployer { get; set; }
        public string CurrentEmployerAddress { get; set; }
        public string EmploymentDateFrom { get; set; }
        public string EmploymentDateTo { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> YearsOfEmployment { get; set; }
        public string SourceOfFundsIds { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual EmploymentStatu EmploymentStatu { get; set; }
        public virtual ModeOfInstruction ModeOfInstruction { get; set; }
        public virtual ModeOfNotification ModeOfNotification { get; set; }
        public virtual SourceOfIncome SourceOfIncome { get; set; }
    }
}
