//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInsCustodyAccountDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid AccountId { get; set; }
        public string CustodianName { get; set; }
        public string Telephone { get; set; }
        public string Address { get; set; }
        public string Fax { get; set; }
        public string CashAccountNumber { get; set; }
        public string SecuritiesAccountNumber { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
