//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountExpectedActivity
    {
        public System.Guid Id { get; set; }
        public System.Guid AccountId { get; set; }
        public string SourceOfFundIs { get; set; }
        public string SourceOfFundsOthers { get; set; }
        public Nullable<int> TopUpoptionId { get; set; }
        public string TopUpoptionOthers { get; set; }
        public Nullable<int> WithdrawalOptionsId { get; set; }
        public string WithdrawalOptionsOthers { get; set; }
        public Nullable<decimal> ExpectedTopUpAmt { get; set; }
        public Nullable<decimal> ExpectedWithdrawalAmt { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual TopUpOption TopUpOption { get; set; }
        public virtual WithdrawalOption WithdrawalOption { get; set; }
    }
}
