//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.AccountAMLResponses = new HashSet<AccountAMLRespons>();
            this.AccountAuthorisedPersons = new HashSet<AccountAuthorisedPerson>();
            this.AccountETIs = new HashSet<AccountETI>();
            this.AccountFileUploads = new HashSet<AccountFileUpload>();
            this.AccountFinancialInvestmentRiskProfiles = new HashSet<AccountFinancialInvestmentRiskProfile>();
            this.AccountInsCustodyAccountDetails = new HashSet<AccountInsCustodyAccountDetail>();
            this.AccountInsTradingContacts = new HashSet<AccountInsTradingContact>();
            this.AccountInstructionEmploymentDetails = new HashSet<AccountInstructionEmploymentDetail>();
            this.AccountInstSignatoriesMandates = new HashSet<AccountInstSignatoriesMandate>();
            this.AccountMembers = new HashSet<AccountMember>();
            this.AccountNextOfKinDetails = new HashSet<AccountNextOfKinDetail>();
            this.AccountSettlementDetails = new HashSet<AccountSettlementDetail>();
        }
    
        public System.Guid Id { get; set; }
        public int AccountTypeId { get; set; }
        public string AccountNumber { get; set; }
        public string CSDNumber { get; set; }
        public string InstitutionClientName { get; set; }
        public string InstitutionalPrincipalBroker { get; set; }
        public string InstitutionNatureOfBusiness { get; set; }
        public Nullable<int> InsstitutionalCountryOfIncorporation { get; set; }
        public string InstitutionRegistrationNumber { get; set; }
        public string MailingAddressFull { get; set; }
        public string MailingAddressCity { get; set; }
        public Nullable<int> InstMailingAddressCountryId { get; set; }
        public string StreetAddressFull { get; set; }
        public string InstStreetAddressCity { get; set; }
        public string InsStreetAddressZipCode { get; set; }
        public Nullable<int> InsStreetAddressCountryId { get; set; }
        public string InsStreetAddressTel { get; set; }
        public string InsStreetAddressFax { get; set; }
        public string InsStreetAddressEmail { get; set; }
        public Nullable<int> SelectApplicableId { get; set; }
        public Nullable<int> RegionalInvestmentId { get; set; }
        public Nullable<int> FrequencyOfStatementsId { get; set; }
        public string DeclarationConvictedOfLaw { get; set; }
        public string DeclarationConvictedOfLawDetails { get; set; }
        public string DeclarationActingAsNominee { get; set; }
        public string DeclarationActingAsNomineeName { get; set; }
        public string DeclarationIWe { get; set; }
        public Nullable<int> SignatureTypeId { get; set; }
        public string InstOtherDetails { get; set; }
        public string CSDFormPath { get; set; }
        public string InstCompanyType { get; set; }
        public Nullable<int> YearsOfWorkExperience { get; set; }
        public string TIN { get; set; }
        public Nullable<int> ExpectedAccountActivityId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> InvestmentTypeId { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> SuccessfulReviewDate { get; set; }
        public Nullable<System.Guid> SuccesfulReviewBy { get; set; }
        public Nullable<System.DateTime> CancelOrRejectDate { get; set; }
        public Nullable<System.Guid> CancelOrRejectBy { get; set; }
        public string CancelOrRejectComment { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual CSDDepositoryParticipantOption CSDDepositoryParticipantOption { get; set; }
        public virtual CSDDepositoryParticipantOption CSDDepositoryParticipantOption1 { get; set; }
        public virtual RegionalInvesmentInterest RegionalInvesmentInterest { get; set; }
        public virtual StatementFrequency StatementFrequency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountAMLRespons> AccountAMLResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountAuthorisedPerson> AccountAuthorisedPersons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountETI> AccountETIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountFileUpload> AccountFileUploads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountFinancialInvestmentRiskProfile> AccountFinancialInvestmentRiskProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountInsCustodyAccountDetail> AccountInsCustodyAccountDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountInsTradingContact> AccountInsTradingContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountInstructionEmploymentDetail> AccountInstructionEmploymentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountInstSignatoriesMandate> AccountInstSignatoriesMandates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountMember> AccountMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountNextOfKinDetail> AccountNextOfKinDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountSettlementDetail> AccountSettlementDetails { get; set; }
        public virtual ExpectedAccountActivity ExpectedAccountActivity { get; set; }
        public virtual InvestmentType InvestmentType { get; set; }
        public virtual ApplicationStatu ApplicationStatu { get; set; }
    }
}
