//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountFinancialInvestmentRiskProfile
    {
        public System.Guid Id { get; set; }
        public System.Guid AccountId { get; set; }
        public Nullable<int> AnnualIncomeId { get; set; }
        public Nullable<int> NetworthId { get; set; }
        public Nullable<int> InvestmentHorizonId { get; set; }
        public Nullable<int> ObjectivesId { get; set; }
        public Nullable<int> InvestmentKnowledgeId { get; set; }
        public Nullable<int> RiskToleranceId { get; set; }
        public string OnlineTradingFacility { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ApproximateAnnualIncome ApproximateAnnualIncome { get; set; }
        public virtual InvestmentHorizon InvestmentHorizon { get; set; }
        public virtual InvestmentKnowledge InvestmentKnowledge { get; set; }
        public virtual NetWorth NetWorth { get; set; }
        public virtual Objective Objective { get; set; }
        public virtual RiskTolerance RiskTolerance { get; set; }
    }
}
