//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountAMLRespons
    {
        public System.Guid Id { get; set; }
        public System.Guid AccountId { get; set; }
        public int QuestionId { get; set; }
        public string YesNo { get; set; }
        public string Rank { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public decimal RatingValue { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual AMLQuestion AMLQuestion { get; set; }
    }
}
