//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountBeneficiary
    {
        public System.Guid Id { get; set; }
        public System.Guid AccountId { get; set; }
        public string Fullname { get; set; }
        public string Phone { get; set; }
        public decimal PercentageAllocation { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Relation { get; set; }
        public Nullable<int> TitleId { get; set; }
        public string OtherTitleDetails { get; set; }
        public string Surname { get; set; }
        public string Othernames { get; set; }
        public Nullable<int> MaritalStatusId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public string BirthDate { get; set; }
        public string PlaceOfBirth { get; set; }
        public Nullable<int> CountryOfOriginId { get; set; }
        public Nullable<int> CountryOfResidenceId { get; set; }
        public Nullable<int> IDCardTypeId { get; set; }
        public string IDNumber { get; set; }
        public string IDPlaceOfIssue { get; set; }
        public string IDIssueDate { get; set; }
        public string IDExpiryDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual IDCardType IDCardType { get; set; }
        public virtual MaritalStatu MaritalStatu { get; set; }
        public virtual Title Title { get; set; }
    }
}
