//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppSetting
    {
        public string AppName { get; set; }
        public string AppCode { get; set; }
        public string Description { get; set; }
        public string BaseUrl { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Phone2 { get; set; }
    }
}
