//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public string BRANCH_CODE { get; set; }
        public string BRANCH_NAME { get; set; }
        public string CITY_CODE { get; set; }
        public string BRANCH_ADDRESS { get; set; }
        public string FAX_ONE { get; set; }
        public string FAX_TWO { get; set; }
        public string PHONE_ONE { get; set; }
        public string PHONE_TWO { get; set; }
        public Nullable<double> POST { get; set; }
        public Nullable<double> LOG_ID { get; set; }
        public string SoftTechCode { get; set; }
    }
}
