//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailServerSetting
    {
        public int ID { get; set; }
        public string EmailAddress { get; set; }
        public string From { get; set; }
        public string HostName { get; set; }
        public string Password { get; set; }
        public string PortNumber { get; set; }
        public string Username { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<int> Flag { get; set; }
        public bool IsCustomer { get; set; }
    }
}
