//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageHistory
    {
        public System.Guid Id { get; set; }
        public string Type { get; set; }
        public string Title { get; set; }
        public string SentTo { get; set; }
        public string MessageContent { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsSent { get; set; }
    }
}
