//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper.Schema
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBLAccountOpeningContext : DbContext
    {
        public DBLAccountOpeningContext()
            : base("name=DBLAccountOpeningContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<AMLQuestion> AMLQuestions { get; set; }
        public virtual DbSet<ApproximateAnnualIncome> ApproximateAnnualIncomes { get; set; }
        public virtual DbSet<AppSetting> AppSettings { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CSDDepositoryParticipantOption> CSDDepositoryParticipantOptions { get; set; }
        public virtual DbSet<DocType> DocTypes { get; set; }
        public virtual DbSet<EmploymentStatu> EmploymentStatus { get; set; }
        public virtual DbSet<IDCardType> IDCardTypes { get; set; }
        public virtual DbSet<InvestmentHorizon> InvestmentHorizons { get; set; }
        public virtual DbSet<InvestmentKnowledge> InvestmentKnowledges { get; set; }
        public virtual DbSet<InvestmentType> InvestmentTypes { get; set; }
        public virtual DbSet<MailServerSetting> MailServerSettings { get; set; }
        public virtual DbSet<MessageHistory> MessageHistories { get; set; }
        public virtual DbSet<ModeOfInstruction> ModeOfInstructions { get; set; }
        public virtual DbSet<ModeOfNotification> ModeOfNotifications { get; set; }
        public virtual DbSet<ModeOfReceivingStatement> ModeOfReceivingStatements { get; set; }
        public virtual DbSet<NetWorth> NetWorths { get; set; }
        public virtual DbSet<Objective> Objectives { get; set; }
        public virtual DbSet<RegionalInvesmentInterest> RegionalInvesmentInterests { get; set; }
        public virtual DbSet<ResidentialStatu> ResidentialStatus { get; set; }
        public virtual DbSet<RiskTolerance> RiskTolerances { get; set; }
        public virtual DbSet<SignatureType> SignatureTypes { get; set; }
        public virtual DbSet<StatementFrequency> StatementFrequencies { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<MaritalStatu> MaritalStatus { get; set; }
        public virtual DbSet<SourceOfIncome> SourceOfIncomes { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AccountAMLRespons> AccountAMLResponses { get; set; }
        public virtual DbSet<AccountAuthorisedPerson> AccountAuthorisedPersons { get; set; }
        public virtual DbSet<AccountETI> AccountETIs { get; set; }
        public virtual DbSet<AccountFileUpload> AccountFileUploads { get; set; }
        public virtual DbSet<AccountFinancialInvestmentRiskProfile> AccountFinancialInvestmentRiskProfiles { get; set; }
        public virtual DbSet<AccountInsCustodyAccountDetail> AccountInsCustodyAccountDetails { get; set; }
        public virtual DbSet<AccountInsTradingContact> AccountInsTradingContacts { get; set; }
        public virtual DbSet<AccountInstructionEmploymentDetail> AccountInstructionEmploymentDetails { get; set; }
        public virtual DbSet<AccountInstSignatoriesMandate> AccountInstSignatoriesMandates { get; set; }
        public virtual DbSet<AccountMember> AccountMembers { get; set; }
        public virtual DbSet<AccountNextOfKinDetail> AccountNextOfKinDetails { get; set; }
        public virtual DbSet<AccountSettlementDetail> AccountSettlementDetails { get; set; }
        public virtual DbSet<FileUploadType> FileUploadTypes { get; set; }
        public virtual DbSet<ExpectedAccountActivity> ExpectedAccountActivities { get; set; }
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<AMLQuestionCategory> AMLQuestionCategories { get; set; }
        public virtual DbSet<ApplicationStatu> ApplicationStatus { get; set; }
    }
}
